// see: https://en.wikipedia.org/wiki/List_of_country_calling_codes
// for list of country/calling codes
import '../../../../generated/l10n.dart';
import '../model/country.dart';

List<Country> countries = [
  Country(
    name: S.current.afghanistan,
    flag: "🇦🇫",
    code: "AF",
    dialCode: "+93",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.aland_islands,
    flag: "🇦🇽",
    code: "AX",
    dialCode: "+358",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.albania,
    flag: "🇦🇱",
    code: "AL",
    dialCode: "+355",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.algeria,
    flag: "🇩🇿",
    code: "DZ",
    dialCode: "+213",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.american_samoa,
    flag: "🇦🇸",
    code: "AS",
    dialCode: "+1684",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.andorra,
    flag: "🇦🇩",
    code: "AD",
    dialCode: "+376",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.angola,
    flag: "🇦🇴",
    code: "AO",
    dialCode: "+244",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.anguilla,
    flag: "🇦🇮",
    code: "AI",
    dialCode: "+1264",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.antarctica,
    flag: "🇦🇶",
    code: "AQ",
    dialCode: "+672",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.antigua_and_barbuda,
    flag: "🇦🇬",
    code: "AG",
    dialCode: "+1268",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.argentina,
    flag: "🇦🇷",
    code: "AR",
    dialCode: "+54",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.armenia,
    flag: "🇦🇲",
    code: "AM",
    dialCode: "+374",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.aruba,
    flag: "🇦🇼",
    code: "AW",
    dialCode: "+297",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.australia,
    flag: "🇦🇺",
    code: "AU",
    dialCode: "+61",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.austria,
    flag: "🇦🇹",
    code: "AT",
    dialCode: "+43",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: S.current.azerbaijan,
    flag: "🇦🇿",
    code: "AZ",
    dialCode: "+994",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.bahamas,
    flag: "🇧🇸",
    code: "BS",
    dialCode: "+1242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.bahrain,
    flag: "🇧🇭",
    code: "BH",
    dialCode: "+973",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.bangladesh,
    flag: "🇧🇩",
    code: "BD",
    dialCode: "+880",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.barbados,
    flag: "🇧🇧",
    code: "BB",
    dialCode: "+1246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.belarus,
    flag: "🇧🇾",
    code: "BY",
    dialCode: "+375",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.belgium,
    flag: "🇧🇪",
    code: "BE",
    dialCode: "+32",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.belize,
    flag: "🇧🇿",
    code: "BZ",
    dialCode: "+501",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.benin,
    flag: "🇧🇯",
    code: "BJ",
    dialCode: "+229",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.bermuda,
    flag: "🇧🇲",
    code: "BM",
    dialCode: "+1441",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.bhutan,
    flag: "🇧🇹",
    code: "BT",
    dialCode: "+975",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.bolivia_plurinational_state_of_bolivia,
    flag: "🇧🇴",
    code: "BO",
    dialCode: "+591",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.bosnia_and_herzegovina,
    flag: "🇧🇦",
    code: "BA",
    dialCode: "+387",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.botswana,
    flag: "🇧🇼",
    code: "BW",
    dialCode: "+267",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.bouvet_island,
    flag: "🇧🇻",
    code: "BV",
    dialCode: "+47",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.brazil,
    flag: "🇧🇷",
    code: "BR",
    dialCode: "+55",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.british_indian_ocean_territory,
    flag: "🇮🇴",
    code: "IO",
    dialCode: "+246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.brunei_darussalam,
    flag: "🇧🇳",
    code: "BN",
    dialCode: "+673",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.bulgaria,
    flag: "🇧🇬",
    code: "BG",
    dialCode: "+359",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.burkina_faso,
    flag: "🇧🇫",
    code: "BF",
    dialCode: "+226",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.burundi,
    flag: "🇧🇮",
    code: "BI",
    dialCode: "+257",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.cambodia,
    flag: "🇰🇭",
    code: "KH",
    dialCode: "+855",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.cameroon,
    flag: "🇨🇲",
    code: "CM",
    dialCode: "+237",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.campione_d_italia,
    flag: "🇮🇹",
    code: "IT",
    dialCode: "+41",
    regionCode: "91",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: S.current.canada,
    flag: "🇨🇦",
    code: "CA",
    dialCode: "+1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.cape_verde,
    flag: "🇨🇻",
    code: "CV",
    dialCode: "+238",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.cayman_islands,
    flag: "🇰🇾",
    code: "KY",
    dialCode: "+345",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.central_african_republic,
    flag: "🇨🇫",
    code: "CF",
    dialCode: "+236",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.chad,
    flag: "🇹🇩",
    code: "TD",
    dialCode: "+235",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.chile,
    flag: "🇨🇱",
    code: "CL",
    dialCode: "+56",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.china,
    flag: "🇨🇳",
    code: "CN",
    dialCode: "+86",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.christmas_island,
    flag: "🇨🇽",
    code: "CX",
    dialCode: "+61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.cocos_keeling_islands,
    flag: "🇨🇨",
    code: "CC",
    dialCode: "+61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.colombia,
    flag: "🇨🇴",
    code: "CO",
    dialCode: "+57",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.comoros,
    flag: "🇰🇲",
    code: "KM",
    dialCode: "+269",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.congo,
    flag: "🇨🇬",
    code: "CG",
    dialCode: "+242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.congo_the_democratic_republic_of_the_congo,
    flag: "🇨🇩",
    code: "CD",
    dialCode: "+243",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.cook_islands,
    flag: "🇨🇰",
    code: "CK",
    dialCode: "+682",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: S.current.costa_rica,
    flag: "🇨🇷",
    code: "CR",
    dialCode: "+506",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.cote_d_ivoire,
    flag: "🇨🇮",
    code: "CI",
    dialCode: "+225",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.croatia,
    flag: "🇭🇷",
    code: "HR",
    dialCode: "+385",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.cuba,
    flag: "🇨🇺",
    code: "CU",
    dialCode: "+53",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.cyprus,
    flag: "🇨🇾",
    code: "CY",
    dialCode: "+357",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.czech_republic,
    flag: "🇨🇿",
    code: "CZ",
    dialCode: "+420",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.denmark,
    flag: "🇩🇰",
    code: "DK",
    dialCode: "+45",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.djibouti,
    flag: "🇩🇯",
    code: "DJ",
    dialCode: "+253",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.dominica,
    flag: "🇩🇲",
    code: "DM",
    dialCode: "+1767",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.dominican_republic,
    flag: "🇩🇴",
    code: "DO",
    dialCode: "+1849",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.ecuador,
    flag: "🇪🇨",
    code: "EC",
    dialCode: "+593",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: S.current.egypt,
    flag: "🇪🇬",
    code: "EG",
    dialCode: "+20",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.el_salvador,
    flag: "🇸🇻",
    code: "SV",
    dialCode: "+503",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.equatorial_guinea,
    flag: "🇬🇶",
    code: "GQ",
    dialCode: "+240",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.eritrea,
    flag: "🇪🇷",
    code: "ER",
    dialCode: "+291",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.estonia,
    flag: "🇪🇪",
    code: "EE",
    dialCode: "+372",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.ethiopia,
    flag: "🇪🇹",
    code: "ET",
    dialCode: "+251",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.falkland_islands_malvinas,
    flag: "🇫🇰",
    code: "FK",
    dialCode: "+500",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: S.current.faroe_islands,
    flag: "🇫🇴",
    code: "FO",
    dialCode: "+298",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.fiji,
    flag: "🇫🇯",
    code: "FJ",
    dialCode: "+679",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.finland,
    flag: "🇫🇮",
    code: "FI",
    dialCode: "+358",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.france,
    flag: "🇫🇷",
    code: "FR",
    dialCode: "+33",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.french_guiana,
    flag: "🇬🇫",
    code: "GF",
    dialCode: "+594",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.french_polynesia,
    flag: "🇵🇫",
    code: "PF",
    dialCode: "+689",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.french_southern_territories,
    flag: "🇹🇫",
    code: "TF",
    dialCode: "+262",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.gabon,
    flag: "🇬🇦",
    code: "GA",
    dialCode: "+241",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.gambia,
    flag: "🇬🇲",
    code: "GM",
    dialCode: "+220",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.georgia,
    flag: "🇬🇪",
    code: "GE",
    dialCode: "+995",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: S.current.germany,
    flag: "🇩🇪",
    code: "DE",
    dialCode: "+49",
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    name: S.current.ghana,
    flag: "🇬🇭",
    code: "GH",
    dialCode: "+233",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.gibraltar,
    flag: "🇬🇮",
    code: "GI",
    dialCode: "+350",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.greece,
    flag: "🇬🇷",
    code: "GR",
    dialCode: "+30",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.greenland,
    flag: "🇬🇱",
    code: "GL",
    dialCode: "+299",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.grenada,
    flag: "🇬🇩",
    code: "GD",
    dialCode: "+1473",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.guadeloupe,
    flag: "🇬🇵",
    code: "GP",
    dialCode: "+590",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.guam,
    flag: "🇬🇺",
    code: "GU",
    dialCode: "+1671",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.guatemala,
    flag: "🇬🇹",
    code: "GT",
    dialCode: "+502",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.guernsey,
    flag: "🇬🇬",
    code: "GG",
    dialCode: "+44",
    regionCode: "1481",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.guinea,
    flag: "🇬🇳",
    code: "GN",
    dialCode: "+224",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: S.current.guinea_bissau,
    flag: "🇬🇼",
    code: "GW",
    dialCode: "+245",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.guyana,
    flag: "🇬🇾",
    code: "GY",
    dialCode: "+592",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.haiti,
    flag: "🇭🇹",
    code: "HT",
    dialCode: "+509",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.heard_island_and_mcdonald_islands,
    flag: "🇭🇲",
    code: "HM",
    dialCode: "+672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.holy_see_vatican_city_state,
    flag: "🇻🇦",
    code: "VA",
    dialCode: "+379",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.honduras,
    flag: "🇭🇳",
    code: "HN",
    dialCode: "+504",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.hong_kong,
    flag: "🇭🇰",
    code: "HK",
    dialCode: "+852",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.hungary,
    flag: "🇭🇺",
    code: "HU",
    dialCode: "+36",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.iceland,
    flag: "🇮🇸",
    code: "IS",
    dialCode: "+354",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: S.current.india,
    flag: "🇮🇳",
    code: "IN",
    dialCode: "+91",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.indonesia,
    flag: "🇮🇩",
    code: "ID",
    dialCode: "+62",
    minLength: 10,
    maxLength: 13,
  ),
  Country(
    name: S.current.iran_islamic_republic_of_iran,
    flag: "🇮🇷",
    code: "IR",
    dialCode: "+98",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.iraq,
    flag: "🇮🇶",
    code: "IQ",
    dialCode: "+964",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.ireland,
    flag: "🇮🇪",
    code: "IE",
    dialCode: "+353",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: S.current.isle_of_man,
    flag: "🇮🇲",
    code: "IM",
    dialCode: "+44",
    regionCode: "1624",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.italy,
    flag: "🇮🇹",
    code: "IT",
    dialCode: "+39",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: S.current.jamaica,
    flag: "🇯🇲",
    code: "JM",
    dialCode: "+1876",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.japan,
    flag: "🇯🇵",
    code: "JP",
    dialCode: "+81",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.jersey,
    flag: "🇯🇪",
    code: "JE",
    dialCode: "+44",
    regionCode: "1534",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.jordan,
    flag: "🇯🇴",
    code: "JO",
    dialCode: "+962",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.kazakhstan,
    flag: "🇰🇿",
    code: "KZ",
    dialCode: "+7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.kenya,
    flag: "🇰🇪",
    code: "KE",
    dialCode: "+254",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.kiribati,
    flag: "🇰🇮",
    code: "KI",
    dialCode: "+686",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: S.current.korea_democratic_people_s_republic_of_korea,
    flag: "🇰🇵",
    code: "KP",
    dialCode: "+850",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.korea_republic_of_south_korea,
    flag: "🇰🇷",
    code: "KR",
    dialCode: "+82",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.kosovo,
    flag: "🇽🇰",
    code: "XK",
    dialCode: "+383",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.kuwait,
    flag: "🇰🇼",
    code: "KW",
    dialCode: "+965",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.kyrgyzstan,
    flag: "🇰🇬",
    code: "KG",
    dialCode: "+996",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.laos,
    flag: "🇱🇦",
    code: "LA",
    dialCode: "+856",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.latvia,
    flag: "🇱🇻",
    code: "LV",
    dialCode: "+371",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.lebanon,
    flag: "🇱🇧",
    code: "LB",
    dialCode: "+961",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.lesotho,
    flag: "🇱🇸",
    code: "LS",
    dialCode: "+266",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.liberia,
    flag: "🇱🇷",
    code: "LR",
    dialCode: "+231",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.libyan_arab_jamahiriya,
    flag: "🇱🇾",
    code: "LY",
    dialCode: "+218",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.liechtenstein,
    flag: "🇱🇮",
    code: "LI",
    dialCode: "+423",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.lithuania,
    flag: "🇱🇹",
    code: "LT",
    dialCode: "+370",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.luxembourg,
    flag: "🇱🇺",
    code: "LU",
    dialCode: "+352",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.macao,
    flag: "🇲🇴",
    code: "MO",
    dialCode: "+853",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.macedonia,
    flag: "🇲🇰",
    code: "MK",
    dialCode: "+389",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.madagascar,
    flag: "🇲🇬",
    code: "MG",
    dialCode: "+261",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.malawi,
    flag: "🇲🇼",
    code: "MW",
    dialCode: "+265",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: S.current.malaysia,
    flag: "🇲🇾",
    code: "MY",
    dialCode: "+60",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.maldives,
    flag: "🇲🇻",
    code: "MV",
    dialCode: "+960",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.mali,
    flag: "🇲🇱",
    code: "ML",
    dialCode: "+223",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.malta,
    flag: "🇲🇹",
    code: "MT",
    dialCode: "+356",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.marshall_islands,
    flag: "🇲🇭",
    code: "MH",
    dialCode: "+692",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.martinique,
    flag: "🇲🇶",
    code: "MQ",
    dialCode: "+596",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.mauritania,
    flag: "🇲🇷",
    code: "MR",
    dialCode: "+222",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.mauritius,
    flag: "🇲🇺",
    code: "MU",
    dialCode: "+230",
    minLength: 7,
    maxLength: 8,
  ),
  Country(
    name: S.current.mayotte,
    flag: "🇾🇹",
    code: "YT",
    dialCode: "+262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.mexico,
    flag: "🇲🇽",
    code: "MX",
    dialCode: "+52",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.micronesia_federated_states_of_micronesia,
    flag: "🇫🇲",
    code: "FM",
    dialCode: "+691",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.moldova,
    flag: "🇲🇩",
    code: "MD",
    dialCode: "+373",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.monaco,
    flag: "🇲🇨",
    code: "MC",
    dialCode: "+377",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.mongolia,
    flag: "🇲🇳",
    code: "MN",
    dialCode: "+976",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.montenegro,
    flag: "🇲🇪",
    code: "ME",
    dialCode: "+382",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.montserrat,
    flag: "🇲🇸",
    code: "MS",
    dialCode: "+1664",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.morocco,
    flag: "🇲🇦",
    code: "MA",
    dialCode: "+212",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.mozambique,
    flag: "🇲🇿",
    code: "MZ",
    dialCode: "+258",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.myanmar,
    flag: "🇲🇲",
    code: "MM",
    dialCode: "+95",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.namibia,
    flag: "🇳🇦",
    code: "NA",
    dialCode: "+264",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.nauru,
    flag: "🇳🇷",
    code: "NR",
    dialCode: "+674",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.nepal,
    flag: "🇳🇵",
    code: "NP",
    dialCode: "+977",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.netherlands,
    flag: "🇳🇱",
    code: "NL",
    dialCode: "+31",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.netherlands_antilles,
    flag: "",
    code: "AN",
    dialCode: "+599",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.new_caledonia,
    flag: "🇳🇨",
    code: "NC",
    dialCode: "+687",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.new_zealand,
    flag: "🇳🇿",
    code: "NZ",
    dialCode: "+64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.nicaragua,
    flag: "🇳🇮",
    code: "NI",
    dialCode: "+505",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.niger,
    flag: "🇳🇪",
    code: "NE",
    dialCode: "+227",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.nigeria,
    flag: "🇳🇬",
    code: "NG",
    dialCode: "+234",
    minLength: 10,
    maxLength: 11,
  ),
  Country(
    name: S.current.niue,
    flag: "🇳🇺",
    code: "NU",
    dialCode: "+683",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: S.current.norfolk_island,
    flag: "🇳🇫",
    code: "NF",
    dialCode: "+672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.northern_mariana_islands,
    flag: "🇲🇵",
    code: "MP",
    dialCode: "+1670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.norway,
    flag: "🇳🇴",
    code: "NO",
    dialCode: "+47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.oman,
    flag: "🇴🇲",
    code: "OM",
    dialCode: "+968",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.pakistan,
    flag: "🇵🇰",
    code: "PK",
    dialCode: "+92",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.palau,
    flag: "🇵🇼",
    code: "PW",
    dialCode: "+680",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.palestine,
    flag: "🇵🇸",
    code: "PS",
    dialCode: "+970",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.panama,
    flag: "🇵🇦",
    code: "PA",
    dialCode: "+507",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.papua_new_guinea,
    flag: "🇵🇬",
    code: "PG",
    dialCode: "+675",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.paraguay,
    flag: "🇵🇾",
    code: "PY",
    dialCode: "+595",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.peru,
    flag: "🇵🇪",
    code: "PE",
    dialCode: "+51",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.philippines,
    flag: "🇵🇭",
    code: "PH",
    dialCode: "+63",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.pitcairn,
    flag: "🇵🇳",
    code: "PN",
    dialCode: "+64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.poland,
    flag: "🇵🇱",
    code: "PL",
    dialCode: "+48",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.portugal,
    flag: "🇵🇹",
    code: "PT",
    dialCode: "+351",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.puerto_rico,
    flag: "🇵🇷",
    code: "PR",
    dialCode: "+1939",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.qatar,
    flag: "🇶🇦",
    code: "QA",
    dialCode: "+974",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.romania,
    flag: "🇷🇴",
    code: "RO",
    dialCode: "+40",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.russia,
    flag: "🇷🇺",
    code: "RU",
    dialCode: "+7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.rwanda,
    flag: "🇷🇼",
    code: "RW",
    dialCode: "+250",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.reunion,
    flag: "🇷🇪",
    code: "RE",
    dialCode: "+262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.saint_barthelemy,
    flag: "🇧🇱",
    code: "BL",
    dialCode: "+590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.saint_helena_ascension_and_tristan_da_cunha,
    flag: "🇸🇭",
    code: "SH",
    dialCode: "+290",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: S.current.saint_kitts_and_nevis,
    flag: "🇰🇳",
    code: "KN",
    dialCode: "+1869",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.saint_lucia,
    flag: "🇱🇨",
    code: "LC",
    dialCode: "+1758",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.saint_martin,
    flag: "🇲🇫",
    code: "MF",
    dialCode: "+590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.saint_pierre_and_miquelon,
    flag: "🇵🇲",
    code: "PM",
    dialCode: "+508",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.saint_vincent_and_the_grenadines,
    flag: "🇻🇨",
    code: "VC",
    dialCode: "+1784",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.samoa,
    flag: "🇼🇸",
    code: "WS",
    dialCode: "+685",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.san_marino,
    flag: "🇸🇲",
    code: "SM",
    dialCode: "+378",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.sao_tome_and_principe,
    flag: "🇸🇹",
    code: "ST",
    dialCode: "+239",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.saudi_arabia,
    flag: "🇸🇦",
    code: "SA",
    dialCode: "+966",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.senegal,
    flag: "🇸🇳",
    code: "SN",
    dialCode: "+221",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.serbia,
    flag: "🇷🇸",
    code: "RS",
    dialCode: "+381",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.seychelles,
    flag: "🇸🇨",
    code: "SC",
    dialCode: "+248",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.sierra_leone,
    flag: "🇸🇱",
    code: "SL",
    dialCode: "+232",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.singapore,
    flag: "🇸🇬",
    code: "SG",
    dialCode: "+65",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.slovakia,
    flag: "🇸🇰",
    code: "SK",
    dialCode: "+421",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.slovenia,
    flag: "🇸🇮",
    code: "SI",
    dialCode: "+386",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.solomon_islands,
    flag: "🇸🇧",
    code: "SB",
    dialCode: "+677",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: S.current.somalia,
    flag: "🇸🇴",
    code: "SO",
    dialCode: "+252",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.south_africa,
    flag: "🇿🇦",
    code: "ZA",
    dialCode: "+27",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.south_sudan,
    flag: "🇸🇸",
    code: "SS",
    dialCode: "+211",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.south_georgia_and_the_south_sandwich_islands,
    flag: "🇬🇸",
    code: "GS",
    dialCode: "+500",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: S.current.spain,
    flag: "🇪🇸",
    code: "ES",
    dialCode: "+34",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.sri_lanka,
    flag: "🇱🇰",
    code: "LK",
    dialCode: "+94",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.sudan,
    flag: "🇸🇩",
    code: "SD",
    dialCode: "+249",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.suriname,
    flag: "🇸🇷",
    code: "SR",
    dialCode: "+597",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.svalbard_and_jan_mayen,
    flag: "🇸🇯",
    code: "SJ",
    dialCode: "+47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.eswatini,
    flag: "🇸🇿",
    code: "SZ",
    dialCode: "+268",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.sweden,
    flag: "🇸🇪",
    code: "SE",
    dialCode: "+46",
    minLength: 7,
    maxLength: 13,
  ),
  Country(
    name: S.current.switzerland,
    flag: "🇨🇭",
    code: "CH",
    dialCode: "+41",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: S.current.syrian_arab_republic,
    flag: "🇸🇾",
    code: "SY",
    dialCode: "+963",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.taiwan,
    flag: "🇹🇼",
    code: "TW",
    dialCode: "+886",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.tajikistan,
    flag: "🇹🇯",
    code: "TJ",
    dialCode: "+992",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.tanzania_united_republic_of_tanzania,
    flag: "🇹🇿",
    code: "TZ",
    dialCode: "+255",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.thailand,
    flag: "🇹🇭",
    code: "TH",
    dialCode: "+66",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.timor_leste,
    flag: "🇹🇱",
    code: "TL",
    dialCode: "+670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.togo,
    flag: "🇹🇬",
    code: "TG",
    dialCode: "+228",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.tokelau,
    flag: "🇹🇰",
    code: "TK",
    dialCode: "+690",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: S.current.tonga,
    flag: "🇹🇴",
    code: "TO",
    dialCode: "+676",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.trinidad_and_tobago,
    flag: "🇹🇹",
    code: "TT",
    dialCode: "+1868",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.tunisia,
    flag: "🇹🇳",
    code: "TN",
    dialCode: "+216",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.turkey,
    flag: "🇹🇷",
    code: "TR",
    dialCode: "+90",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.turkmenistan,
    flag: "🇹🇲",
    code: "TM",
    dialCode: "+993",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.turks_and_caicos_islands,
    flag: "🇹🇨",
    code: "TC",
    dialCode: "+1649",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.tuvalu,
    flag: "🇹🇻",
    code: "TV",
    dialCode: "+688",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.uganda,
    flag: "🇺🇬",
    code: "UG",
    dialCode: "+256",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.ukraine,
    flag: "🇺🇦",
    code: "UA",
    dialCode: "+380",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.united_arab_emirates,
    flag: "🇦🇪",
    code: "AE",
    dialCode: "+971",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.united_kingdom,
    flag: "🇬🇧",
    code: "GB",
    dialCode: "+44",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.united_states,
    flag: "🇺🇸",
    code: "US",
    dialCode: "+1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.uruguay,
    flag: "🇺🇾",
    code: "UY",
    dialCode: "+598",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.uzbekistan,
    flag: "🇺🇿",
    code: "UZ",
    dialCode: "+998",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.vanuatu,
    flag: "🇻🇺",
    code: "VU",
    dialCode: "+678",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.venezuela_bolivarian_republic_of_venezuela,
    flag: "🇻🇪",
    code: "VE",
    dialCode: "+58",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.vietnam,
    flag: "🇻🇳",
    code: "VN",
    dialCode: "+84",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: S.current.virgin_islands_british,
    flag: "🇻🇬",
    code: "VG",
    dialCode: "+1284",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.virgin_islands_u_s,
    flag: "🇻🇮",
    code: "VI",
    dialCode: "+1340",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: S.current.wallis_and_futuna,
    flag: "🇼🇫",
    code: "WF",
    dialCode: "+681",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: S.current.yemen,
    flag: "🇾🇪",
    code: "YE",
    dialCode: "+967",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.zambia,
    flag: "🇿🇲",
    code: "ZM",
    dialCode: "+260",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.zimbabwe,
    flag: "🇿🇼",
    code: "ZW",
    dialCode: "+263",
    minLength: 9,
    maxLength: 9,
  ),
];